# OPCUA CI build using EPICS ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

# This is YAML - indentation levels are crucial

# Set the 'name:' properties to values that work for you

name: opcua build and end-to-end test

# Trigger on pushes and PRs to any branch
on:
  push:
    paths-ignore:
      - 'documentation/*'
      - '**/*.html'
      - '**/*.md'
  pull_request:

env:
  SETUP_PATH: .ci-local:.ci
  MODULES: "gtest"
  GTEST: "v1.0.1"
  BASE_HOOK: ".ci-local/base.patch"
  BASE_RECURSIVE: NO
  encrypted_178ee45b7f75_pass: ${{ secrets.encrypted_178ee45b7f75_pass }}

jobs:
  build-linux:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    # Set environment variables from matrix parameters
    env:
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      BASE: ${{ matrix.base }}
      UASDK: ${{ matrix.uasdk }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "7.0"
            uasdk: "1.6.3"
            name: "7.0 Ub-20 SDK-1.6.3"

          - os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "R3.15.5"
            uasdk: "1.6.3"
            name: "3.15.5 Ub-20 SDK-1.6.3"

          - os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "3.15"
            uasdk: "1.6.3"
            name: "3.15 Ub-20 SDK-1.6.3"

          - os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "7.0"
            uasdk: "1.7.2"
            name: "7.0 Ub-20 SDK-1.7.2"

          - os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "R3.15.5"
            uasdk: "1.7.2"
            name: "3.15.5 Ub-20 SDK-1.7.2"

          - os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "3.15"
            uasdk: "1.7.2"
            name: "3.15 Ub-20 SDK-1.7.2"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Prepare and compile dependencies
      run: |
        python .ci-local/install-sdk.py
        python .ci/cue.py prepare
    - name: Build main module
      run: python .ci/cue.py build
    - name: Run main module tests
      run: python .ci/cue.py test
    - name: Collect and show test results
      run: python .ci/cue.py test-results
    - name: Install end2end test dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libfaketime faketime
        sudo pip3 install pytest opcua pyepics
        sudo pip3 install run-iocsh -i https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple
    - name: Run end2end tests
      run: |
        python .ci/cue.py exec make -C end2endTest/server
        python .ci/cue.py exec pytest -v end2endTest/opcua_test_cases.py
